version: '3.8'

services:
  web:
    build: ./backend                 # 1. Dokploy builds the Dockerfile here
    image: pos-core-app      # 2. It saves the finished image with this name
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis:7-alpine

  