version: '3.8'

services:
  web:
    build: ./backend                 # 1. Dokploy builds the Dockerfile here
    image: pos-core-app      # 2. It saves the finished image with this name
    command: gunicorn myproject.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis:7-alpine

  celery:
    image: pos-core-app      # 3. Celery skips building and just reuses the finished image!
    command: celery -A myproject worker -l INFO
    env_file:
      - .env
    depends_on:
      - web                  # Waits for the 'web' service to finish building the image
      - redis

  celery-beat:
    image: pos-core-app      # 4. Celery Beat also reuses the image!
    command: celery -A myproject beat -l INFO
    env_file:
      - .env
    depends_on:
      - web
      - redis