# Generated by Django 5.0.14 on 2026-04-13 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_tenantsettings'),
        ('returns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnorder',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='common.branch'),
        ),
    ]
