# Generated by Django 5.0.14 on 2026-09-05 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_accountingsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingsettings',
            name='asset_prefix',
            field=models.CharField(default='1000', max_length=8),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='equity_prefix',
            field=models.CharField(default='3000', max_length=8),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='expense_prefix',
            field=models.CharField(default='5000', max_length=8),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='liability_prefix',
            field=models.CharField(default='2000', max_length=8),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='revenue_prefix',
            field=models.CharField(default='4000', max_length=8),
        ),
    ]
