# Generated by Django 5.0.14 on 2026-02-27 22:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='expense_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Fuel & Power', 'Fuel & Power'), ('Internet & Communication', 'Internet & Communication'), ('Maintenance', 'Maintenance'), ('Staff Welfare', 'Staff Welfare'), ('Office Supplies', 'Office Supplies'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
