# Generated by Django 5.0.14 on 2026-03-12 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_tenantsettings'),
        ('finance', '0003_expense_expense_date_alter_expense_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='scope',
            field=models.CharField(choices=[('Branch', 'Branch Expense'), ('Corporate', 'Corporate/HQ Expense')], default='Branch', max_length=200),
        ),
        migrations.AlterField(
            model_name='expense',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='common.branch'),
        ),
    ]
