# Generated by Django 5.0.14 on 2026-02-13 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0002_initial'),
        ('inventory', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='users.tenant'),
        ),
        migrations.AddField(
            model_name='inventorybatch',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='common.branch'),
        ),
        migrations.AddField(
            model_name='inventorybatch',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='users.tenant'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='users.tenant'),
        ),
        migrations.AddField(
            model_name='inventorybatch',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='inventory.product'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='dest_branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_transfers', to='common.branch'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='source_branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_transfers', to='common.branch'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='users.tenant'),
        ),
        migrations.AddField(
            model_name='transferitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product'),
        ),
        migrations.AddField(
            model_name='transferitem',
            name='transfer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.stocktransfer'),
        ),
    ]
