# Generated by Django 5.0.14 on 2026-02-16 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit_type',
            field=models.CharField(choices=[('Weight', 'Weight'), ('Unit', 'Unit'), ('Carton', 'Carton')], max_length=10),
        ),
    ]
