# Generated by Django 5.0.14 on 2026-02-16 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_product_unit_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorybatch',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Expired', 'Expired'), ('Quarantined', 'Quarantined'), ('Depeleted', 'Depleted')], default='Active', max_length=20),
        ),
    ]
