# Generated by Django 5.0.14 on 2026-02-16 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_inventorybatch_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorybatch',
            name='cost_price_at_receipt',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
