# Generated by Django 5.0.14 on 2026-07-07 13:31

import inventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_purchaseinvoice_purchaseinvoiceitem_purchaseorder_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='debt_limit',
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='id',
            field=models.CharField(default=inventory.models.generate_purchase_id, editable=False, max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='supplierledger',
            name='transaction_type',
            field=models.CharField(choices=[('Purchase', 'Purchase'), ('Repayment', 'Repayment'), ('Return', 'Return')], max_length=20),
        ),
    ]
