# Generated by Django 5.0.14 on 2026-07-07 13:47

import inventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_remove_supplier_debt_limit_alter_purchaseorder_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='id',
            field=models.CharField(default=inventory.models.generate_receipt_id, editable=False, max_length=12, primary_key=True, serialize=False),
        ),
    ]
