# Generated by Django 5.0.14 on 2026-07-21 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_supplierpayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplierpayment',
            name='order',
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_payments', to='inventory.purchaseinvoice'),
        ),
        migrations.AlterField(
            model_name='supplierledger',
            name='transaction_type',
            field=models.CharField(choices=[('Purchase', 'Purchase'), ('Credit_payment', 'Credit_payment'), ('Return', 'Return')], max_length=20),
        ),
    ]
