# Generated by Django 5.0.14 on 2026-08-29 12:17

import inventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_remove_supplierpayment_order_supplierpayment_invoice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='id',
            field=models.CharField(default=inventory.models.generate_supplier_id, editable=False, max_length=12, primary_key=True, serialize=False),
        ),
    ]
