# Generated by Django 5.0.14 on 2026-02-16 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='customer_snapshot',
            field=models.JSONField(blank=True, default=dict, help_text='Snapshot of customer details at time of sale'),
        ),
    ]
