# Generated by Django 5.0.14 on 2026-02-16 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_salesorder_customer_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='cost_price_at_sale',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
