# Generated by Django 5.0.14 on 2026-02-18 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_payment_branch_payment_processed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Transfer', 'Transfer'), ('POS', 'POS'), ('Credit', 'Credit')], max_length=20),
        ),
    ]
