# Generated by Django 5.0.14 on 2026-02-24 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_initial'),
        ('sales', '0006_alter_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerledger',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='The branch where this transaction occurred', null=True, on_delete=django.db.models.deletion.PROTECT, to='common.branch'),
        ),
    ]
