# Generated by Django 5.0.14 on 2026-02-24 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_customer_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerledger',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=100000.0, max_digits=12),
        ),
    ]
