# Generated by Django 5.0.14 on 2026-02-24 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_customerledger_notes_alter_customer_credit_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerledger',
            name='reference_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
