# Generated by Django 5.0.14 on 2026-03-02 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_shiftreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
