# Generated by Django 5.0.14 on 2026-03-02 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_salesorder_discount_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftreport',
            name='shift_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
