# Generated by Django 5.0.14 on 2026-03-02 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_shiftreport_shift_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftreport',
            name='shift_code',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
