# Generated by Django 5.0.14 on 2026-03-04 09:04

import sales.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_alter_shiftreport_shift_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='id',
            field=models.CharField(default=sales.models.generate_receipt_id, editable=False, max_length=8, primary_key=True, serialize=False),
        ),
    ]
