# Generated by Django 5.0.14 on 2026-03-04 09:10

import sales.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_alter_salesorder_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.CharField(default=sales.models.generate_customer_id, editable=False, primary_key=True, serialize=False),
        ),
    ]
