# Generated by Django 5.0.14 on 2026-03-16 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0017_alter_customer_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customerledger',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Transfer', 'Transfer'), ('POS', 'POS'), ('Credit', 'Credit')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customerledger',
            name='processed_by',
            field=models.ForeignKey(blank=True, help_text='The cashier who collected this debt payment', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
