# Generated by Django 5.0.14 on 2026-03-16 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0018_customerledger_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='sales.customer'),
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_type',
            field=models.CharField(choices=[('Sales', 'Sales'), ('Debt Payment', 'Debt Payment')], default='Sales', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='sales.salesorder'),
        ),
    ]
