# Generated by Django 5.0.14 on 2026-03-16 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0019_payment_customer_payment_transaction_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerledger',
            name='payment_method',
        ),
    ]
