# Generated by Django 5.0.14 on 2026-03-20 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0020_remove_customerledger_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerledger',
            name='transaction_type',
            field=models.CharField(choices=[('Sale', 'Sale'), ('Payment', 'Payment'), ('Return', 'Return')], max_length=20),
        ),
    ]
