# Generated by Django 5.0.14 on 2026-03-31 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0021_alter_customerledger_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=1000000.0, max_digits=12),
        ),
    ]
