# Generated by Django 5.0.14 on 2026-04-20 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0022_alter_customer_credit_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Voided', 'Voided')], default='Completed', max_length=20),
        ),
    ]
