# Generated by Django 5.0.14 on 2026-05-01 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0024_voidrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='transaction_type',
            field=models.CharField(choices=[('Sales', 'Sales'), ('Debt Payment', 'Debt Payment'), ('Refund', 'Refund')], default='Sales', max_length=20),
        ),
    ]
