# Generated by Django 5.0.14 on 2026-05-02 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0025_alter_payment_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='sales.shiftreport'),
        ),
    ]
