# Generated by Django 5.0.14 on 2026-05-02 22:28

from django.db import migrations
from django.utils import timezone
import random
import string

def backfill_missing_shifts(apps, schema_editor):
    # 1. We MUST use apps.get_model inside migrations, not direct imports!
    SalesOrder = apps.get_model('sales', 'SalesOrder')
    ShiftReport = apps.get_model('sales', 'ShiftReport')
    
    # Find all ghost sales
    ghost_sales = SalesOrder.objects.filter(shift__isnull=True)
    
    for order in ghost_sales:
        # Try to find a shift for this cashier that started BEFORE the sale happened
        # We order by -start_time to get the most recent one prior to the sale
        historical_shift = ShiftReport.objects.filter(
            cashier=order.user,
            branch=order.branch,
            tenant=order.tenant,
            start_time__lte=order.created_at
        ).order_by('-start_time').first()
        
        # If the cashier truly never had a shift that day, we must create a dummy one
        if not historical_shift:
            # Note: Model custom .save() methods are often bypassed in migrations, 
            # so we must generate the shift_code manually here.
            timestamp = order.created_at.strftime("%Y%m%d-%H%M")
            suffix = ''.join(random.choices(string.digits, k=4))
            shift_code = f"legacy-{timestamp}-{suffix}"
            
            historical_shift = ShiftReport.objects.create(
                tenant=order.tenant,
                branch=order.branch,
                cashier=order.user,
                status='Closed', # Keep it closed so it doesn't mess up current operations
                start_time=order.created_at,
                end_time=order.created_at,
                shift_code=shift_code,
                notes="System-generated shift for historical data migration."
            )
            
        # Attach the shift to the order and save
        order.shift = historical_shift
        order.save()


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0026_salesorder_shift'),
    ]

    operations = [migrations.RunPython(backfill_missing_shifts, reverse_code=migrations.RunPython.noop),
    ]
