# Generated by Django 5.0.14 on 2026-05-02 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0027_auto_20260502_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='sales.shiftreport'),
        ),
    ]
