# Generated by Django 5.0.14 on 2026-08-29 12:17

import sales.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0028_alter_salesorder_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.CharField(default=sales.models.generate_customer_id, editable=False, max_length=50, primary_key=True, serialize=False),
        ),
    ]
