# Generated by Django 5.0.14 on 2026-08-31 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0029_alter_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Pending', 'Pending'), ('Failed', 'Failed'), ('Voided', 'Voided')], default='Completed', max_length=20),
        ),
    ]
