# Generated by Django 5.0.14 on 2026-09-01 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0030_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerledger',
            name='transaction_type',
            field=models.CharField(choices=[('Sale', 'Sale'), ('Payment', 'Payment'), ('Return', 'Return'), ('Void Sale', 'Void Sale')], max_length=20),
        ),
    ]
