# Generated by Django 5.0.14 on 2026-09-05 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0031_alter_customerledger_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerledger',
            name='transaction_type',
            field=models.CharField(choices=[('Sale', 'Sale'), ('Payment', 'Payment'), ('Return', 'Return'), ('Void Sale', 'Void Sale'), ('Reversal', 'Reversal')], max_length=20),
        ),
    ]
