# Generated by Django 5.0.14 on 2026-02-24 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_name', models.CharField(default='My Business', max_length=255)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('currency_symbol', models.CharField(default='₦', max_length=5)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage (e.g., 7.5)', max_digits=5)),
                ('receipt_footer', models.TextField(blank=True, default='Thank you for your patronage!')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='users.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
