# Generated by Django 5.0.14 on 2026-04-20 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_tenantsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantsettings',
            name='void_approval_roles',
            field=models.JSONField(default=list, help_text="List of roles allowed to approve voids, e.g., ['Admin', 'Branch_Manager']"),
        ),
    ]
